version: "3"
services:
  app:
    image: instapy/instapy:latest
    container_name: "${COMPOSE_PROJECT_NAME}_app"
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=0
      - INSTAPY_WORKSPACE=/code/InstaPy
    volumes:
      - ./:/code
